[[redirects]]
  from = "/pc-se/serier/samtliga"
  to = "https://content.viaplay.se/pc-se/serier/samtliga"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}